lists: # Add lists of interest from arxiv, e.g.,
  - "cs.LG"
  - "cs.AI"
  - "cs.CV"
  - "cs.GL"
  - "cs.NE"
bot:
  class_name: SlackBot
  parameters:
    token: <your token here>
    channel: <your chat id here>
criteria: # Add some keywords to detect topics of interest, e.g.,
  - interpretability
  - xai
  - explainability
summarizer: BulletListSumarizer
gpu_layers: 0  # Set here the n. of layers to move to the GPU
context_length: 2000  # Context length
